### ISSUE TITLE
RangeError: Maximum call stack size exceeded (on v0.1.13)

### ISSUE THREAD

**Issue by prbroadfoot** [tailwindlabs/tailwindcss-jit#173]
### What version of @tailwindcss/jit are you using?

0.1.13

### What version of Node.js are you using?

15.11.0

### What browser are you using?

N/A

### What operating system are you using?

Arch

### Reproduction repository

https://github.com/prbroadfoot/tailwind-jit-error-reproduction

Apologies if I'm doing something silly because I don't have experience with Tailwind and not a lot with npm either.

Here's what I did to reproduce the error with the repository I provided:

npm install
TAILWIND_MODE=build npx postcss styles.css -o main.css --verbose

```
RangeError: Maximum call stack size exceeded
    at candidatePermutations (/home/paul/Desktop/tailwind-jit-error-reproduction/node_modules/@tailwindcss/jit/src/lib/generateRules.js:19:32)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/home/paul/Desktop/tailwind-jit-error-reproduction/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/home/paul/Desktop/tailwind-jit-error-reproduction/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/home/paul/Desktop/tailwind-jit-error-reproduction/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/home/paul/Desktop/tailwind-jit-error-reproduction/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
```

**Comment by adamwathan** [comment]
Thanks, can you test with v0.1.14? I published a fix for a similar issue that might also fix this one 👍🏻

**Comment by prbroadfoot** [comment]
Thanks, bumping up to v0.1.14 fixed the issue in the reproduction repo and also my original project
