### ISSUE TITLE
Not able to get to work in Vite

### ISSUE THREAD

**Issue by tauzN** [tailwindlabs/tailwindcss-jit#18]
I am not able to get it to work in Vite with Vue. This might be a problem with Vite.
I think the error is related to some relative path mapping in Vite.
It was working as expected with "regular" tailwindcss

Node 15.11.0
Vite 2.0.5
Vue 3.0.6
tailwindcss/jit 0.1.0

```
// index.css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

The project starts as expected
```
//Console output

PS D:\git\Journalizer 2> npm run dev

> journalizer2@2.0.0 dev
> vite

Pre-bundling dependencies:      
  vue
  dayjs
  dayjs/locale/da
  dayjs/plugin/relativeTime     
  dayjs/plugin/customParseFormat
  (...and 6 more)
(this will be run only when your dependencies or config have changed)

  vite v2.0.5 dev server running at:

  > Network:  https://192.168.87.101:443/
  > Local:    https://localhost.test:443/

  ready in 1049ms.
```

but throws these errors when accessing the webserver in the browser:

```
18.40.22 [vite] Internal server error: ENOENT: no such file or directory, stat '/git/Journalizer%202/src/index.css'
  Plugin: vite:css
  File: D:/git/Journalizer 2/src/index.css
      at Object.statSync (node:fs:1142:3)
      at trackModified (D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:187:26)
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:652:38
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\index.js:34:49
      at LazyResult.runOnRoot (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:303:16)
      at LazyResult.runAsync (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:355:26)
      at LazyResult.async (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:205:30)
      at LazyResult.then (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:190:17)
18.40.22 [vite] Internal server error: ENOENT: no such file or directory, stat '/git/Journalizer%202/tailwind.config.js' 
  Plugin: vite:css
  File: D:/git/Journalizer 2/src/App.vue?vue&type=style&index=0&lang.postcss
      at Object.statSync (node:fs:1142:3)
      at trackModified (D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:187:26)
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:652:38
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\index.js:34:49
      at LazyResult.runOnRoot (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:303:16)
      at LazyResult.runAsync (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:355:26)
      at LazyResult.async (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:205:30)
      at LazyResult.then (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:190:17)
18.40.22 [vite] Internal server error: ENOENT: no such file or directory, stat '/git/Journalizer%202/tailwind.config.js' 
  Plugin: vite:css
  File: D:/git/Journalizer 2/src/views/Auth.vue?vue&type=style&index=0&lang.postcss
      at Object.statSync (node:fs:1142:3)
      at trackModified (D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:187:26)
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:652:38
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\index.js:34:49
      at LazyResult.runOnRoot (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:303:16)
      at LazyResult.runAsync (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:355:26)
      at LazyResult.async (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:205:30)
      at LazyResult.then (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:190:17)
18.40.22 [vite] Internal server error: ENOENT: no such file or directory, stat '/git/Journalizer%202/tailwind.config.js' 
  Plugin: vite:css
  File: D:/git/Journalizer 2/src/views/AuthEnd.vue?vue&type=style&index=0&lang.postcss
      at Object.statSync (node:fs:1142:3)
      at trackModified (D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:187:26)
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:652:38
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\index.js:34:49
      at LazyResult.runOnRoot (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:303:16)
      at LazyResult.runAsync (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:355:26)
      at LazyResult.async (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:205:30)
      at LazyResult.then (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:190:17)
18.40.22 [vite] Internal server error: ENOENT: no such file or directory, stat '/git/Journalizer%202/tailwind.config.js' 
  Plugin: vite:css
  File: D:/git/Journalizer 2/src/views/Config.vue?vue&type=style&index=0&lang.postcss
      at Object.statSync (node:fs:1142:3)
      at trackModified (D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:187:26)
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:652:38
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\index.js:34:49
      at LazyResult.runOnRoot (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:303:16)
      at LazyResult.runAsync (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:355:26)
      at LazyResult.async (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:205:30)
      at LazyResult.then (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:190:17)
18.40.22 [vite] Internal server error: ENOENT: no such file or directory, stat '/git/Journalizer%202/tailwind.config.js' 
  Plugin: vite:css
  File: D:/git/Journalizer 2/src/views/Listitem/Listitem.vue?vue&type=style&index=0&scoped=true&lang.postcss
      at Object.statSync (node:fs:1142:3)
      at trackModified (D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:187:26)
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\lib\setupContext.js:652:38
      at D:\git\Journalizer 2\node_modules\@tailwindcss\jit\src\index.js:34:49
      at LazyResult.runOnRoot (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:303:16)
      at LazyResult.runAsync (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:355:26)
      at LazyResult.async (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:205:30)
      at LazyResult.then (D:\git\Journalizer 2\node_modules\postcss\lib\lazy-result.js:190:17)
```

**Comment by tauzN** [comment]
I can access 
```https://localhost.test/src/App.vue?vue&type=style&index=0```
in the browser, but not with &lang params
```https://localhost.test/src/App.vue?vue&type=style&index=0&lang.css```

**Comment by overflowedBuffer** [comment]
can you get it to generate in a Css file?
noting works for me with Vite . it's like regular tailwind

**Comment by bramaudi** [comment]
I got the same error with Snowpack, maybe tailwindcss jit is still incompatible with esbuild-based bundler

**Comment by tauzN** [comment]
I can confirm that it works as expected when renaming project folder to 'Journalizer-2' (no space)

**Comment by overflowedBuffer** [comment]
> I can confirm that it works as expected when renaming project folder to 'Journalizer-2' (no space)

is it working with vue + vite ? does it generate chained classes?

**Comment by bymayo** [comment]
I also get the `ENOENT: no such file or directory, stat` issue, running it through Gulp / PostCSS

**Comment by bramaudi** [comment]
> I can confirm that it works as expected when renaming project folder to 'Journalizer-2' (no space)

Not sure about that, my project folder name is in single word, i'm using Linux btw.

**Comment by tauzN** [comment]
This seem unrelated to Vite. This issue description is more fitting #22
