### ISSUE TITLE
Postcss 7 support

### ISSUE THREAD

**Issue by coderinblack08** [tailwindlabs/tailwindcss-jit#19]
Is there or will there be postcss7 support?

**Comment by onmax** [comment]
I don't think so: https://github.com/tailwindlabs/tailwindcss-jit/issues/17#issuecomment-799616186 😐
Are you getting an error trying to update?
I really want to use this new compiler because I struggle a lot with the dev panel in the browser being buggy. But I am getting this error:
```
ERROR in ./src/styles.scss (./node_modules/@angular-builders/custom-webpack/node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--13-3!./node_modules/@angular-builders/custom-webpack/node_modules/sass-loader/dist/cjs.js??ref--13-4!./node_modules/postcss-loader/src??postcss!./src/styles.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin tailwindcss-jit requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/home/max/dalion/sdk-web-dalion/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/home/max/dalion/sdk-web-dalion/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/home/max/dalion/sdk-web-dalion/node_modules/postcss-loader/node_modules/postcss/lib/postcss.js:55:10)
    at /home/max/dalion/sdk-web-dalion/node_modules/postcss-loader/src/index.js:140:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

ERROR in Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin tailwindcss-jit requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/home/max/dalion/sdk-web-dalion/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/home/max/dalion/sdk-web-dalion/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/home/max/dalion/sdk-web-dalion/node_modules/postcss-loader/node_modules/postcss/lib/postcss.js:55:10)
    at /home/max/dalion/sdk-web-dalion/node_modules/postcss-loader/src/index.js:140:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I was using PostCSS7 before, becuase I was getting the error with the PostCSS8 so I had to follow these instructions: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by coderinblack08** [comment]
So to wrap this issue up, "Currently the JIT project only supports PostCSS 8, correct. We may do a compat build like we do for Tailwind but not a priority right now".

**Comment by vesper8** [comment]
I'm so confused because I do have PostCSS 8 installed but I keep getting this error anyway `PostCSS plugin tailwindcss-jit requires PostCSS 8`

Is something tailwindcss-jit not currently compatible with Vue 2 via vue-cli 4 ?

**Comment by nshutijean** [comment]
> I'm so confused because I do have PostCSS 8 installed but I keep getting this error anyway `PostCSS plugin tailwindcss-jit requires PostCSS 8`
> 
> Is something tailwindcss-jit not currently compatible with Vue 2 via vue-cli 4 ?

Same thing is happening to me as and i'm using Vue 3 + Typescript. Any workaround?
