### ISSUE TITLE
Vite: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by richardtallent** [tailwindlabs/tailwindcss-jit#29]
Looking forward to playing with this! Didn't get far today, it bailed when loading the first page under vite:

```
Unknown error from PostCSS plugin. Your current PostCSS version is 8.2.6, but autoprefixer uses 7.0.35. Perhaps this is the 
source of the error below.
2:31:45 PM [vite] Internal server error: Maximum call stack size exceeded
  Plugin: vite:css
  File: C:/project-path/src/styles/base.css
      at Function.keys (<anonymous>)
      at _clone (C:\project-path\node_modules\autoprefixer\lib\prefixer.js:22:42)
      at _clone (C:\project-path\node_modules\autoprefixer\lib\prefixer.js:38:17)
      at _clone (C:\project-path\node_modules\autoprefixer\lib\prefixer.js:38:17)
      at _clone (C:\project-path\node_modules\autoprefixer\lib\prefixer.js:38:17)
      at _clone (C:\project-path\node_modules\autoprefixer\lib\prefixer.js:38:17)
      at _clone (C:\project-path\node_modules\autoprefixer\lib\prefixer.js:38:17)
      at _clone (C:\project-path\node_modules\autoprefixer\lib\prefixer.js:38:17)
      at _clone (C:\project-path\node_modules\autoprefixer\lib\prefixer.js:38:17)
      at _clone (C:\project-path\node_modules\autoprefixer\lib\prefixer.js:38:17)
```

The `base.css` file contains only the three main `@apply` statements for tailwind:
```CSS
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Here's my tailwind.config.js file, nothing special:

```JS
module.exports = {
	purge: ["./index.html", "./src/**/*.{vue,js,ts}"],
	darkMode: "class",
	theme: {
		extend: {},
	},
	variants: {
		extend: {},
	},
	plugins: [],
}
```

I'm using vite 2.1.0 with vue 3.0.7.

**Comment by DevNvll** [comment]
Same using next@10.0.5

**Comment by adamwathan** [comment]
Try updating to the very latest autoprefixer, I have seen this occur myself as well and that solved it for me:

```
npm install -D autoprefixer@latest
```

**Comment by DmiPet** [comment]
@richardtallent @DevNvll try running `npm i -D autoprefixer@latest`, that did the trick for me

**Comment by jpsca** [comment]
Updating to the latest `autoprefix` solved it for me as well, using plain `postcss`, no framework.

**Comment by opdavies** [comment]
> Try updating to the very latest autoprefixer

I had the same issue in a Drupal theme using Webpack Encore. Updating to the latest autoprefixer fixes it for me too.

**Comment by adamwathan** [comment]
Going to close since updating autoprefixer seems to be the solution!

**Comment by richardtallent** [comment]
Confirmed, all good here now! 🥇 :)
