### ISSUE TITLE
Cannot find stdin on track modified

### ISSUE THREAD

**Issue by cschmatzler** [tailwindlabs/tailwindcss-jit#74]
Trying out the new compiler with snowpack. Very minimal setup, with `@snowpack/plugin-postcss` added to the snowpack config and my postcss config looking like

```
module.exports = {
  plugins: {
    '@tailwindcss/jit': {},
    autoprefixer: {},
  }
};
```
Jusing the normal `tailwindcss` PostCSS plugin works just fine, but with JIT I am getting the following error on running `yarn snowpack build`:

```
[snowpack] ! building dependencies...
(node:1378370) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: postcss
Error: ENOENT: no such file or directory, stat '/home/cschmatzler/development/papertrail/lynx/assets/stdin'
    at Object.statSync (fs.js:1086:3)
    at trackModified (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/@tailwindcss/jit/src/lib/setupContext.js:188:26)
    at /home/cschmatzler/development/papertrail/lynx/assets/node_modules/@tailwindcss/jit/src/lib/setupContext.js:653:38
    at /home/cschmatzler/development/papertrail/lynx/assets/node_modules/@tailwindcss/jit/src/index.js:34:49
    at LazyResult.runOnRoot (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss/lib/lazy-result.js:355:26)
    at LazyResult.async (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss/lib/lazy-result.js:190:17)
    at /home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss-cli/index.js:233:10
    at async Promise.all (index 0) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/cschmatzler/development/papertrail/lynx/assets/stdin'
}
    at makeError (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.transform (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/@snowpack/plugin-postcss/plugin.js:13:24)
    at async runPipelineTransformStep (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/snowpack/lib/index.js:75331:32)
    at async Object.buildFile (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/snowpack/lib/index.js:75416:29)
    at async FileBuilder.buildFile (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/snowpack/lib/index.js:111929:15)
    at async run (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/snowpack/lib/index.js:50375:29)
```

**Comment by adamwathan** [comment]
Hey! Can you provide an actual reproduction repository so I have something to test locally?

**Comment by pbougie** [comment]
@adamwathan You can use https://github.com/pbougie/hugo-tailwind. Just follow the instructions in the README to build and run each case. Requires Docker Desktop. There is nothing else to install. The source folder gets mounted so you can make changes.

**Comment by cschmatzler** [comment]
> Hey! Can you provide an actual reproduction repository so I have something to test locally?

https://github.com/cschmatzler/tailwind-jit-issue

Here you go!

**Comment by cschmatzler** [comment]
The problem seems to come from `@snowpack/plugin-postcss` in https://github.com/snowpackjs/snowpack/blob/dc503c84e77da61ab9e3cbd47bb5b7502dd3f479/plugins/plugin-postcss/worker.js#L14 using `stdin` as processing source.
Not sure about whether this needs to be fixed in the snowpack or tailwind plugin, but it's definitely a regression from the non-jit version.

**Comment by adamwathan** [comment]
Yeah need to think about what should be done here. Currently we expect a file path for the CSS and that is used as a cache key to make things efficient. If using Snowpack with like Vue or something where every Vue file can have its own <style> block, Tailwind will be run for every single Vue file and we need to know the file it's coming from. If we use `stdin` for every single input you can't really get any caching and builds will be slower.

Something we can probably figure out at least and at least make work.

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/4323180/111492569-292ee680-8713-11eb-9007-74633353828a.png">

**Comment by hamstu** [comment]
Came here to raise the same issue. 

A hacky workaround for now is to just `touch stdin` in the directory, though it sounds like @adamwathan is saying we're not getting some caching benefits ☹️ 

That said, will probably still keep this in my project for now as the benefits of jit still appear to outweigh the cost.

**Comment by rohfle** [comment]
See related open issue at https://github.com/snowpackjs/snowpack/issues/2916

Theres a quickfix at https://github.com/snowpackjs/snowpack/commit/8ac85f6dff57ac49a9668dd5687d635ce054081d, where the full path is used instead of stdin, but there are still some problems in dev mode that are being worked on
