### ISSUE TITLE
Hugo + Tailwind JIT not working

### ISSUE THREAD

**Issue by pbougie** [tailwindlabs/tailwindcss-jit#79]
I'm trying to implement [Hugo](https://gohugo.io/) with Tailwind CSS + JIT. I have it working without JIT. However, when I add JIT it throws the following error:

```
Error: Error building site: POSTCSS: failed to transform "css/index.css" (text/css): Error: ENOENT: no such file or directory, stat '/app/stdin'
    at Object.statSync (fs.js:1086:3)
    at trackModified (/node_modules/@tailwindcss/jit/src/lib/setupContext.js:188:26)
    at /node_modules/@tailwindcss/jit/src/lib/setupContext.js:653:38
    at /node_modules/@tailwindcss/jit/src/index.js:34:49
    at LazyResult.runOnRoot (/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/node_modules/postcss/lib/lazy-result.js:355:26)
    at LazyResult.async (/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (/node_modules/postcss/lib/lazy-result.js:190:17)
    at /node_modules/postcss-cli/index.js:233:10
    at async Promise.all (index 0) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/app/stdin'
}
```

I have created a test project using Docker to reproduce the issue. Visit https://github.com/pbougie/hugo-tailwind and follow the instructions in the README to build and run each case.

**Comment by adamwathan** [comment]
Hey thanks! This is going to ultimately be the same underlying problem as #74 so going to close and track there. It is something to do with feeding your CSS to the JIT over stdin instead of from an actual file.
